name: full_calender
description: The Full Calendar Flutter Library facilitates seamless conversion between solar, lunar calendars and Julian days, with a focus on the Vietnamese lunar calendar system.
version: 1.2.86
homepage: https://github.com/hiimBugCreator/full_calendar/

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:

